Add MD for worker intensive

diff --git a/kustomize-units/cluster-manifests/kubeadm-capm3/base/kubeadm-capm3-cluster.yaml b/kustomize-units/cluster-manifests/kubeadm-capm3/base/kubeadm-capm3-cluster.yaml
--- a/kustomize-units/cluster-manifests/kubeadm-capm3/base/kubeadm-capm3-cluster.yaml
+++ b/kustomize-units/cluster-manifests/kubeadm-capm3/base/kubeadm-capm3-cluster.yaml
@@ -236,8 +236,80 @@ spec:
         - if [ ! -f "/var/lib/grub-init" ]; then
         - touch "/var/lib/grub-init"
         - current_grub=$(grep '^GRUB_CMDLINE_LINUX_DEFAULT=' /etc/default/grub | tail -1 | sed -e "s/^[^=]*=[\"']\\?//" -e "s/['\"]$//")
-        - enable_sriov="iommu=pt intel_iommu=on "
-        - next_grub="$current_grub $enable_sriov ${ADDITIONAL_GRUB_SETTINGS}"
+        - next_grub="$current_grub ${ENABLE_SRIOV} ${HUGE_PAGES}"
+        # No need for a timeout. Nobody attends
+        - sed -i -e '/GRUB_TIMEOUT=5/ d' /etc/default/grub
+        # Delete the old command-line
+        - sed -i -e '/^GRUB_CMDLINE_LINUX_DEFAULT=/ d' /etc/default/grub
+        # No wait on reboot (first considered as failed)
+        - echo "GRUB_RECORDFAIL_TIMEOUT=1" >> /etc/default/grub
+        - echo "GRUB_CMDLINE_LINUX_DEFAULT=\"$next_grub\"" >> /etc/default/grub
+        - update-grub
+        - cloud-init clean --reboot
+        - fi
+        - netplan apply
+        - sleep 60
+        - ip a
+        - ip r
+        - export HTTP_PROXY=${HTTP_PROXY} HTTPS_PROXY=${HTTP_PROXY} NO_PROXY=${NO_PROXY}
+        - export http_proxy=${HTTP_PROXY} https_proxy=${HTTP_PROXY} no_proxy=${NO_PROXY}
+        - apt update
+        - apt install -y apt-transport-https ca-certificates curl gnupg lsb-release gpg-agent
+        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
+        - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
+        - apt  update
+        - apt install -y containerd.io
+        - mkdir -p /etc/containerd
+        - containerd config default | sudo tee /etc/containerd/config.toml
+        - systemctl daemon-reload && systemctl restart containerd.service
+        - echo "fs.inotify.max_user_watches = 524288" >> /etc/sysctl.conf
+        - echo "fs.inotify.max_user_instances = 512" >> /etc/sysctl.conf
+        - echo 1 > /proc/sys/net/ipv4/ip_forward
+        - modprobe br_netfilter
+        - echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables 
+        - sysctl --system
+        # Remove default mirroring configuration for k8s.gcr.io as it can't coexist with registry config dir
+        - sed -i '/k8s.gcr.io/d' /etc/containerd/config.toml
+        - grep -q config_path /etc/containerd/config.toml || echo "[plugins.\"io.containerd.grpc.v1.cri\".registry]\n  config_path = \"/etc/containerd/registry.d\"" >>  /etc/containerd/config.toml
+        - systemctl restart containerd.service
+        - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo -E apt-key add -
+        - |
+          cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
+          deb https://apt.kubernetes.io/ kubernetes-xenial main
+          EOF
+        - apt update
+        - apt install -qy kubelet=${KUBEADM_VERSION} kubeadm=${KUBEADM_VERSION} kubectl=${KUBEADM_VERSION}
+        - apt-mark hold kubelet kubeadm kubectl
+      users:
+        - name: ubuntu
+          groups: users
+          sudo: ALL=(ALL) NOPASSWD:ALL
+          shell: /bin/bash
+          sshAuthorizedKeys:
+            - ${SSH_PUBLIC_KEY}
+---
+apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
+kind: KubeadmConfigTemplate
+metadata:
+  name: ${CLUSTER_NAME}-worker-intensive
+  namespace: default
+spec:
+  template:
+    spec:
+      files: []
+      joinConfiguration:
+        nodeRegistration:
+          kubeletExtraArgs:
+            provider-id: metal3://{{ ds.meta_data.uuid }}
+            feature-gates: "TopologyManager=true"
+            topology-manager-policy: "best-effort"
+          name: '{{ ds.meta_data.local_hostname }}'
+      preKubeadmCommands:
+        # From kanod_image_builder grub-init
+        - if [ ! -f "/var/lib/grub-init" ]; then
+        - touch "/var/lib/grub-init"
+        - current_grub=$(grep '^GRUB_CMDLINE_LINUX_DEFAULT=' /etc/default/grub | tail -1 | sed -e "s/^[^=]*=[\"']\\?//" -e "s/['\"]$//")
+        - next_grub="$current_grub ${HUGE_PAGES}"
         # No need for a timeout. Nobody attends
         - sed -i -e '/GRUB_TIMEOUT=5/ d' /etc/default/grub
         # Delete the old command-line
@@ -354,5 +426,39 @@ spec:
         apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
         kind: Metal3MachineTemplate
         name: ${CLUSTER_NAME}-worker-sriov
+      nodeDrainTimeout: 0s
+      version: ${K8S_VERSION}
+---
+apiVersion: cluster.x-k8s.io/v1beta1
+kind: MachineDeployment
+metadata:
+  labels:
+    cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
+    nodepool: worker-intensive
+  name: ${CLUSTER_NAME}-md-intensive
+  namespace: default
+spec:
+  clusterName: ${CLUSTER_NAME}
+  replicas: ${WORKER_INTENSIVE_REPLICAS:=0}
+  selector:
+    matchLabels:
+      cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
+      nodepool: worker-intensive
+  template:
+    metadata:
+      labels: 
+        cluster.x-k8s.io/cluster-name: ${CLUSTER_NAME}
+        nodepool: worker-intensive
+    spec:
+      bootstrap:
+        configRef:
+          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
+          kind: KubeadmConfigTemplate
+          name: ${CLUSTER_NAME}-worker-intensive
+      clusterName: ${CLUSTER_NAME}
+      infrastructureRef:
+        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
+        kind: Metal3MachineTemplate
+        name: ${CLUSTER_NAME}-worker-intensive
       nodeDrainTimeout: 0s
       version: ${K8S_VERSION}
